---
version: '3'

services:
  ccd-user-profile-api:
    image: hmcts/ccd-user-profile-api
    environment:
      USER_PROFILE_DB_HOST: ccd-shared-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "${DB_USE_SSL}"
      USER_PROFILE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_definition,sscs
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ccd-shared-database
    links:
      - ccd-shared-database
      - service-auth-provider-api

  ccd-definition-store-api:
    image: hmcts/ccd-definition-store-api
    environment:
      DEFINITION_STORE_DB_HOST: ccd-shared-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,sscs
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4451:4451
    depends_on:
      - ccd-shared-database
      - ccd-user-profile-api
    links:
      - ccd-shared-database
      - ccd-user-profile-api
      - idam-api
      - service-auth-provider-api

  ccd-data-store-api:
    image: hmcts/ccd-data-store-api
    environment:
      DATA_STORE_DB_HOST: ccd-shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,sscs
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: http://idam-api:8080
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4452:4452
    depends_on:
      - ccd-shared-database
      - ccd-user-profile-api
      - ccd-definition-store-api
    links:
      - ccd-shared-database
      - ccd-user-profile-api
      - ccd-definition-store-api
      - idam-api
      - service-auth-provider-api

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      IDAM_SUPERUSER_EMAIL: ccd@hmcts.net
      SPRING_DATASOURCE_URL: jdbc:postgresql://ccd-shared-database:5432/idam
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
      SPRING_MAIL_HOST: smtp-server
      IDAM_TESTING_SUPPORT_ENABLED: "true"
      NOTIFY_API_KEY: AAAAAAAAAAAAAAAA
      NOTIFY_CMC_ACTIVATE_USER_TEMPLATE: 76aa8695-64e8-4afd-ae13-bc8385302b1f
      IDAM_SECRET: idam_test_secret
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_CCD_GATEWAY: "${OAUTH2_CLIENT_CCD_GATEWAY}"
      IDAM_API_OAUTH2_CLIENT_CLIENT_SECRETS_SSCS: QM5RQQ53LZFOSIXJ
      IDAM_CCD_WHITELIST: http://localhost:3451/oauth2redirect
      NOTIFY: "false"
      NOTIFY_CMC_WELCOME_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE: fake
      NOTIFY_SSCS_WELCOME_USER_TEMPLATE: fake
      NOTIFY_RESET_PASSWORD_TEMPLATE: fake
      NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE: fake
      NOTIFY_CCD_ACTIVATE_USER_TEMPLATE: fake
      REFORM_SERVICE_NAME: idam-api
      REFORM_TEAM: idam
      REFORM_ENVIRONMENT: local
      http_proxy:
      https_proxy:
      no_proxy:
    ports:
      - 4501:8080
    links:
      - smtp-server
      - ccd-shared-database
    depends_on:
      - ccd-shared-database
      - smtp-server

  service-auth-provider-api:
    image: hmcts/service-auth-provider-app
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICE_KEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICE_KEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICE_KEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICE_KEYS_SSCS: "${IDAM_KEY_SSCS}"
      TESTING_SUPPORT_ENABLED:

  smtp-server:
    image: mailhog/mailhog
    ports:
      - 1025:1025


  ccd-shared-database:
    build: ../database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DB_USERNAME:
      DB_PASSWORD:
    ports:
      - 5000:5432
    volumes:
      - ccd-docker-ccd-shared-database-data:/var/lib/postgresql/data

  pdf-service-api:
    image: docker.artifactory.reform.hmcts.net/reform/pdf-service-api
    environment:
      - JAVA_OPTS=-Xms8m -Xmx256m -Djava.security.egd=file:/dev/./urandom -XX:MaxMetaspaceSize=128m
      - S2S_URL=http://service-auth-provider-api:8080
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_NAME=pdf-service
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
    ports:
      - 5500:5500
    healthcheck:
      retries: 40


  document-management-store:
    image: hmcts/dm-store:latest
    command: --wait-for-database 30
    environment:
      - SERVER_PORT=8080
      - IDAM_SUPERUSER_EMAIL
      - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAC
      - GOV_NOTIFY_API_KEY
      - SPRING_DATASOURCE_URL=jdbc:postgresql://document-management-store-database:5432/evidence
      - SPRING_DATASOURCE_USERNAME=evidence
      - SPRING_DATASOURCE_PASSWORD=evidence
      - SPRING_PROFILES_ACTIVE=dev
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
      - IDAM_USER_BASE_URI=http://idam-api:8080
      - IDAM_S2S_BASE_URI=http://service-auth-provider-api:8080
      - http_proxy=
      - https_proxy=
      - no_proxy=
#      logging env vars
      - ROOT_APPENDER=JSON_CONSOLE
      - JSON_CONSOLE_PRETTY_PRINT=false
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=dm-store
      - REFORM_TEAM=evidence
      - REFORM_ENVIRONMENT=docker
#      healthcheck env vars
      - PACKAGES_ENVIRONMENT=docker
      - PACKAGES_PROJECT=evidence
      - PACKAGES_NAME=dm-store
      - PACKAGES_VERSION=unkown
#      debug mode
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 4603:8080
    links:
     - document-management-store-database
     - idam-api
     - service-auth-provider-api
    depends_on:
     - document-management-store-database
     - idam-api
     - service-auth-provider-api

  document-management-store-database:
    image: hmcts/dm-store-db:latest

  sscs-tribunals-case-api:
    image: hmcts:sscs-tribunals-case-api
    environment:
      EMAIL_SERVER_HOST: localhost
      EMAIL_SERVER_PORT: 1025
      PDF_API_URL: http://pdf-service-api:5500
      CORE_CASE_DATA_API_URL: http://ccd-data-store-api:4452
      IDAM_URL: http://idam-api:8080
      IDAM_S2S_AUTH: http://service-auth-provider-api:8080
      DOCUMENT_MANAGEMENT_URL: http://document-management-store:8080
      IDAM_OAUTH2_REDIRECT_URL: https://localhost:9000/poc
    ports:
      - 8181:8080

volumes:
  ccd-docker-ccd-shared-database-data:
