---
version: '3'

services:
  ccd-case-management-web:
    image: "${CCD_CASE_MANAGEMENT_WEB_USE_LOCAL-hmctspublic.azurecr.io/}ccd/case-management-web:${CCD_CASE_MANAGEMENT_WEB_TAG:-latest}"
    container_name: ccd-case-management-web
    environment:
      IDAM_LOGIN_URL: http://localhost:3501/login
      CCD_GATEWAY_BASE_URL: http://localhost:3453
      CCD_ACTIVITY_BASE_URL:
      DM_GATEWAY_BASE_URL: https://api-gateway.dev.dm.reform.hmcts.net
      OAUTH2_CLIENT_ID: ccd_gateway
    ports:
      - 3451:3451
    depends_on:
      - ccd-api-gateway

  ccd-api-gateway:
    image: "${CCD_API_GATEWAY_USE_LOCAL-hmctspublic.azurecr.io/}ccd/api-gateway-web:${CCD_API_GATEWAY_TAG:-latest}"
    container_name: ccd-api-gateway-web
    environment:
      IDAM_BASE_URL: http://sidam-api:5000
      IDAM_USER_URL: http://sidam-api:5000
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_OAUTH2_LOGOUT_ENDPOINT: http://sidam-api:5000/session/:token
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: ccd_gateway_secret
      IDAM_OAUTH2_TOKEN_ENDPOINT: http://sidam-api:5000/oauth2/token
      ADDRESS_LOOKUP_TOKEN:
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      PROXY_DOCUMENT_MANAGEMENT: http://dm-store:5005
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api

  idam-web-admin:
    image: hmctspublic.azurecr.io/idam/web-admin:preview
    environment:
      JAVA_OPTS: -Xms128m -Xmx512m
      STRATEGIC_SERVICE_URL: http://sidam-api:5000
      STRATEGIC_PUBLIC_URL: http://idam-web-public:3501
    ports:
      - 8082:8080
    links:
      - sidam-api
    depends_on:
      - sidam-api

  idam-web-public:
    image: hmctspublic.azurecr.io/idam/web-public:preview
    environment:
     STRATEGIC_SERVICE_URL: http://sidam-api:5000
     IDAM_CONTINUE_URL_VALIDATOR_ENFORCE_TLS: "false"
     REFORM_SERVICE_NAME: sidam-api
     REFORM_TEAM: idam
     REFORM_ENVIRONMENT: local
     JAVA_OPTS: -Xms128m -Xmx512m
    ports:
      - 3501:8080
    links:
      - sidam-api
    depends_on:
      - sidam-api
