version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1
    container_name: ccd-kibana
    networks:
      - ccd-network
    ports: 
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://ccd-elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://ccd-elasticsearch:9200
networks:
  ccd-network:
    external: true
