version: '2.4'
services:
  ccd-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:ccd-latest"
    container_name: ccd-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - compose_default

  sscs-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:sscs-latest"
    container_name: sscs-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - compose_default

networks:
  compose_default:
    external: true