version: '2.4'
services:

  sscs-logstash:
    image: logstash:ccd-sscs-logstash-latest
    container_name: sscs-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true

