---
version: '3'

services:
  rpa-em-ccd-orchestrator:
    image: hmctspublic.azurecr.io/em/ccdorc:latest
    environment:
      - SERVER_PORT=8080
      - CALLBACK_DOMAIN=rpa-em-ccd-orchestrator
      - IDAM_API_BASE_URI=http://sidam-api:5000
      - OPEN_ID_API_BASE_URI=http://sidam-api:5000/o
      - S2S_BASE_URI=http://service-auth-provider-api:8080
      - APPINSIGHTS_INSTRUMENTATIONKEY=test_app
      - DM_STORE_APP_URL=http://dm-store:5005
      - CCD_DATA_API_URL=http://ccd-data-store-api:4452
      - EM_STITCHING_API_URL=http://stitching-api:8080
      - ENABLE_LIQUIBASE=true
      # these environment variables are used by java-logging library
      - JSON_CONSOLE_PRETTY_PRINT=false
      - ROOT_LOGGING_LEVEL=WARN
      - REFORM_SERVICE_TYPE=java
      - REFORM_SERVICE_NAME=rpa-em-ccd-orchestrator
      - REFORM_TEAM=em-ccd-orchestrator
      - REFORM_ENVIRONMENT=docker
    ports:
      - 4623:8080