---
version: '3'

services:
  sscs-bulk-scan:
    image: "hmcts/sscs-bulk-scan:${SSCS_BULK_SCAN_TAG:-latest}"
    environment:
      CORE_CASE_DATA_API_URL: http://ccd-data-store-api:4452
      IDAM_S2S-AUTH_URL: http://service-auth-provider-api:8080
      DOCUMENT_MANAGEMENT_URL: http://dm-store:4506
    ports:
      - 8090:8090