---
version: '3'

services:
  sscs-tribunals-case-api:
    image: hmctspublic/sscs/tribunals-case-api
    environment:
      EMAIL_SERVER_HOST: smtp-server
      EMAIL_SERVER_PORT: 1025
      PDF_API_URL: http://pdf-service-api:5500
      CORE_CASE_DATA_API_URL: http://ccd-data-store-api:4452
      IDAM_URL: http://sidam-api:5000
      IDAM_S2S_AUTH: http://service-auth-provider-api:8080
      DOCUMENT_MANAGEMENT_URL: http://dm-store:4506
      IDAM_OAUTH2_REDIRECT_URL: https://localhost:9000/poc
    ports:
      - 8080:8080