---
version: '3'

services:
  stitching-api:
    image: hmctspublic.azurecr.io/em/stitching:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stitching-db:5432/emstitch
      - SPRING_DATASOURCE_USERNAME=emstitch
      - SPRING_DATASOURCE_PASSWORD=emstitch
      - S2S_BASE_URI=http://service-auth-provider-api:8080
      - IDAM_API_BASE_URI=${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}
      - OPEN_ID_API_BASE_URI=${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/o
      - ENABLE_LIQUIBASE=true
      - APPINSIGHTS_INSTRUMENTATIONKEY=test-key
      - DM_STORE_APP_URL=http://dm-store:5005
      - DOCMOSIS_ACCESS_KEY=${DOCMOSIS_ACCESS_KEY}
      - S2S_NAMES_WHITELIST:jui_webapp,em_ccd_orchestrator,em_gw,sscs
    depends_on:
#      - idam-api
      - rse-idam-simulator
#      - ccd-test-stubs-service
      - stitching-db
      - dm-store
    links:
      - stitching-db
      - dm-store
      - service-auth-provider-api
#     - idam-api
      - rse-idam-simulator
#      - ccd-test-stubs-service
    ports:
      - 4630:8080
    extra_hosts:
      - "docmosis.aat.platform.hmcts.net:10.10.24.121"
    networks:
      - ccd-network

  stitching-db:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_DB=emstitch
      - POSTGRES_USER=emstitch
      - POSTGRES_PASSWORD=emstitch
    ports:
      - 5678:5432
    networks:
      - ccd-network
networks:
  ccd-network:
    external: true
