---
version: '3'

services:
  stitching-api:
    image: hmctspublic.azurecr.io/em/stitching:latest
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stitching-db:5432/emstitch
      - SPRING_DATASOURCE_USERNAME=emstitch
      - SPRING_DATASOURCE_PASSWORD=emstitch
      - S2S_BASE_URI=http://service-auth-provider-api:8080
      - IDAM_API_BASE_URI=http://sidam-api:5000
      - ENABLE_LIQUIBASE=true
      - APPINSIGHTS_INSTRUMENTATIONKEY=test-key
      - DM_STORE_APP_URL=http://dm-store:5005
      - S2S_NAMES_WHITELIST:jui_webapp,em_ccd_orchestrator,em_gw,sscs
    depends_on:
      - stitching-db
      - dm-store
    links:
      - stitching-db
      - dm-store
    ports:
      - 4630:8080
    extra_hosts:
      - "docmosis-development.platform.hmcts.net:172.16.0.6"

  stitching-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=emstitch
      - POSTGRES_USER=emstitch
      - POSTGRES_PASSWORD=emstitch
    ports:
      - 5678:5432